---

- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: reload systemctl
  shell: systemctl daemon-reload

- name: restart rabbitmq
  become: yes
  service: name=rabbitmq-server state=restarted
