---

- name: install datadog agent
  import_role:
    name: datadog.dd.agent
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
  when: datadog.enabled
  tags: datadog

- name: update datadog configuration
  become: true
  become_user: dd-agent
  blockinfile:
    path: /etc/datadog-agent/datadog.yaml
    block: |
      site: {{ datadog.site }}
      hostname: {{ datadog.hostname }}
  tags: datadog

- name: Add redisdb config
  template:
    src: "datadog/redisdb.yaml.j2"
    dest: "/etc/datadog-agent/conf.d/redisdb.d/conf.yaml"
    owner: dd-agent
    group: dd-agent
    mode: 0640
  tags: datadog

- name: Restart Datadog service
  ansible.builtin.service:
    name: datadog-agent
    state: restarted
  tags: datadog
