
- name: Install Redis
  apt:
    name:
      - redis-server
    update_cache: "{{ apt_update_cache }}"
    state: present
  tags: redis

- name: Set redis config
  become: yes
  lineinfile:
    dest: /etc/redis/redis.conf
    line: '{{ item.key }} {{ item.value }}'
  with_dict: "{{ redis_config }}"
  tags: redis

- name: Highlight manual redis restart needed
  debug:
    msg: "Redis was not restarted. To be done manually if needed."
  tags: redis
