- name: Install AWS cli
  apt:
    name: awscli
  tags:
    - packages
    - aws_setup

- name: Create aws config directory for {{ postgresql_user }}
  become: yes
  file:
    path: '{{ postgresql_user_home_dir }}/.aws'
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: 0700
    state: directory
  tags:
    - aws_setup

- name: Set up ~/.aws/credentials for {{ postgresql_user }}
  become: yes
  template:
    src: "aws_credentials.j2"
    dest: "{{ postgresql_user_home_dir }}/.aws/credentials"
    group: "{{ postgresql_user }}"
    owner: "{{ postgresql_user }}"
    mode: 0700
    backup: yes
  tags:
    - aws_setup
