# Virtualenv

- name: Create the superset virtualenv.
  command: "{{ virtualenv_python_version }} -m venv {{ superset_virtualenv_dir }}"
  args:
    creates: "{{ superset_virtualenv_dir }}/bin/"
  tags:
    - superset
    - celery

- name: Change ownership of superset virtualenv.
  file:
    dest: "{{ superset_virtualenv_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  tags:
    - superset
    - celery

- name: Create the virtualenv post script to set environment variables.
  template:
    src: superset/superset_postactivate_script.sh.j2
    dest: "{{ superset_virtualenv_dir }}/bin/postactivate"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0750
    backup: yes
  tags:
    - superset
    - celery

- name: Install packages required by Superset in the virtualenv.
  pip:
    virtualenv: "{{ superset_virtualenv_dir }}"
    name:
      - psycopg2-binary
      - email_validator
      - gunicorn
      - gevent
      - MarkupSafe==2.0.1
  tags: superset

- name: Install CommCare Analytics
  pip:
    name: 'git+https://github.com/dimagi/commcare-analytics@{{ superset_ketchup_version }}'
    state: forcereinstall
    virtualenv: "{{ superset_virtualenv_dir }}"
  tags: superset

- name: Create run directory
  file:
    path: "{{ run_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0775
    state: directory
  tags:
    - superset
    - celery

# Create config directory and files

- name: Create {{ superset_project_dir }}.
  file:
    path: "{{ superset_project_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0750
    state: directory
  tags: superset

- name: Create {{ superset_shared_dir }}.
  file:
    path: "{{ superset_shared_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0750
    state: directory
  tags: superset

- name: Create the superset_config.py file
  template:
    src: superset/superset_config.py.j2
    dest: "{{ superset_project_dir }}/superset_config.py"
    owner: "{{ ansible_user }}"
    group: "{{ app_group }}"
    mode: 0640
    backup: yes
  tags: superset


- name: Run Superset database migrations.
  become: yes
  become_user: "{{ app_user }}"
  environment: "{{ superset_environment }}"
  shell: "{{ superset_virtualenv_dir }}/bin/superset db upgrade"
  tags: superset

- name: Run Superset initialization.
  become: yes
  become_user: "{{ app_user }}"
  environment: "{{ superset_environment }}"
  shell: "{{ superset_virtualenv_dir }}/bin/superset init"
  tags: superset

- name: Create Superset admin user
  become: yes
  become_user: "{{ app_user }}"
  environment: "{{ superset_environment }}"
  shell: |
    {{ superset_virtualenv_dir }}/bin/superset fab create-admin \
                    --username {{ superset_username }} \
                    --firstname {{ superset_firstname }} \
                    --lastname {{ superset_lastname }} \
                    --email {{ superset_email }} \
                    --password {{ superset_admin_password }} \
                    || true
  tags: superset

# Supervisor files

- name: Create the Supervisor start script.
  template:
    src: superset/superset_start_script.j2
    dest: "{{ superset_virtualenv_dir }}/bin/superset_start"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0750
    backup: yes
  tags: superset

- name: Create the Superset Supervisor config file.
  template:
    src: superset/superset_supervisor_config.j2
    dest: /etc/supervisor/conf.d/superset.conf
    backup: yes
  tags: superset

- name: Create the Celery default start script.
  template:
    src: superset/celery_default_start_script.j2
    dest: "{{ superset_virtualenv_dir }}/bin/celery_default_start"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0750
    backup: yes
  tags:
    - supervisor
    - celery

- name: Create the Celery Supervisor config file.
  template:
    src: superset/celery_default_supervisor_config.j2
    dest: /etc/supervisor/conf.d/{{ app_name }}_celery_default.conf
    backup: yes
  tags:
    - superset
    - celery

- name: Create the Celery Beat Supervisor config file.
  template:
    src: superset/celery_beat_supervisor_config.j2
    dest: /etc/supervisor/conf.d/{{ app_name }}_celery_beat.conf
    backup: yes
  tags:
    - superset
    - celery

- name: Create log directory "{{ log_dir }}"
  file:
    path: "{{ log_dir }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  tags:
    - superset
    - celery

- name: Create Supervisor log files.
  copy:
    content: ""
    dest: "{{ log_dir }}/{{ item }}"
    force: no
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0644
  with_items:
    - supervisor.log
    - celery.log
    - celery_beat.log
  tags:
    - superset
    - celery

- name: Re-read the Superset supervisor config files.
  supervisorctl:
    name: "{{ item }}"
    state: present
  with_items:
    - superset
    - "{{ app_name }}_celery_default"
    - "{{ app_name }}_celery_beat"
  tags:
    - superset
    - celery

- name: Restart the Superset Supervisor process.
  supervisorctl:
    name: "{{ item }}"
    state: restarted
  with_items:
    - superset
    - "{{ app_name }}_celery_default"
    - "{{ app_name }}_celery_beat"
  tags:
    - superset
    - celery

- name: Create superset nginx config.
  template:
    src: nginx/superset_nginx_without_ssl_config.j2
    dest: /etc/nginx/sites-available/superset.conf
    backup: yes
  when: "not superset_ssl_enabled"
  tags:
    - superset
    - nginx

- name: Enable superset nginx config.
  file:
    src: /etc/nginx/sites-available/superset.conf
    dest: /etc/nginx/sites-enabled/superset.conf
    state: link
  when: "not superset_ssl_enabled"
  tags:
    - superset
    - nginx

- name: Test & reload nginx config.
  shell: nginx -t && nginx -s reload
  tags:
    - superset
    - nginx

